version: '3'

services:
  mysql:
    build: ./
    image: echo-clean_mysql
    container_name: mysql
    hostname: mysql
    tty: true
    privileged: true
    ports:
      - "3306:3306"
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma 
    hostname: pma
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
       - 8080:80
