version: '3'

services:
  mysql:
    build: ./
    image: echo-clean_mysql
    container_name: mysql
    hostname: mysql
    tty: true
    privileged: true
    ports:
      - "3306:3306"
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
